services:
  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    restart: unless-stopped

  backend_php:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - ./backend:/app
    depends_on:
      - db
    restart: unless-stopped

  frontend_next:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - ./frontend:/app
    restart: unless-stopped

  db:
    image: mysql:8.0
    # OPRAVA: Přidána sekce ports
    ports:
      # Mapuje port 3306 z kontejneru na port 3306 na vašem lokálním stroji.
      # Můžete změnit lokální port, pokud už ho máte obsazený, např. "3307:3306".
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    restart: unless-stopped

volumes:
  caddy_data:
  db_data: