api_platform:
    title: 'Rymarov Helper API'
    version: '1.0.0'
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/Controller'

    defaults:
        normalization_context:
            groups: ['ask:read']
        denormalization_context:
            groups: ['ask:write']
